/**
 * core/team_aliases.js — shared by both bots
 * Team nickname → search term for !score and fixture matching.
 * Keys lowercase; values match against API team names (case-insensitive).
 */

const LEAGUES = [
  "epl",
  "la_liga",
  "bundesliga",
  "ligue_1",
  "serie_a",
  "champions_league",
  "europa_league",
  "conference_league",
];

const LEAGUE_LABELS = {
  epl: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Premier League",
  la_liga: "🇪🇸 La Liga",
  bundesliga: "🇩🇪 Bundesliga",
  ligue_1: "🇫🇷 Ligue 1",
  serie_a: "🇮🇹 Serie A",
  champions_league: "⭐ Champions League",
  europa_league: "🟠 Europa League",
  conference_league: "🟢 Conference League",
  overall: "🏆 Overall",
};

const LEAGUE_EMOJIS = {
  epl: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  la_liga: "🇪🇸",
  bundesliga: "🇩🇪",
  ligue_1: "🇫🇷",
  serie_a: "🇮🇹",
  champions_league: "⭐",
  europa_league: "🟠",
  conference_league: "🟢",
};

const TEAM_ALIASES = {
  city: "manchester city",
  "man city": "manchester city",
  mancity: "manchester city",
  mcfc: "manchester city",
  "man utd": "manchester united",
  "man united": "manchester united",
  manu: "manchester united",
  united: "manchester united",
  yanited: "manchester united",
  mufc: "manchester united",
  spurs: "tottenham",
  thfc: "tottenham",
  "the blues": "everton",
  blues: "everton",
  toffees: "everton",
  "the toffees": "everton",
  efc: "everton",
  villa: "aston villa",
  avfc: "aston villa",
  wolves: "wolverhampton",
  forest: "nottingham",
  nffc: "nottingham",
  toon: "newcastle",
  toons: "newcastle",
  "the toon": "newcastle",
  magpies: "newcastle",
  barcodes: "newcastle",
  barcode: "newcastle",
  gunners: "arsenal",
  "the gunners": "arsenal",
  afc: "arsenal",
  reds: "liverpool",
  "the reds": "liverpool",
  lfc: "liverpool",
  hammers: "west ham",
  "the hammers": "west ham",
  cherries: "bournemouth",
  seagulls: "brighton",
  palace: "crystal palace",
  eagles: "crystal palace",
  cottagers: "fulham",
  saints: "southampton",
  clarets: "burnley",
  "black cats": "sunderland",
  leeds: "leeds",
  lufc: "leeds",
  real: "real madrid",
  madrid: "real madrid",
  barca: "barcelona",
  barça: "barcelona",
  atletico: "atletico madrid",
  atleti: "atletico madrid",
  betis: "real betis",
  sociedad: "real sociedad",
  athletic: "athletic bilbao",
  bilbao: "athletic bilbao",
  celta: "celta de vigo",
  rayo: "rayo vallecano",
  bayern: "bayern munich",
  bvb: "borussia dortmund",
  dortmund: "borussia dortmund",
  leverkusen: "bayer leverkusen",
  bayer: "bayer leverkusen",
  gladbach: "monchengladbach",
  leipzig: "rb leipzig",
  werder: "werder bremen",
  bremen: "werder bremen",
  frankfurt: "eintracht frankfurt",
  koln: "cologne",
  köln: "cologne",
  cologne: "cologne",
  hsv: "hamburger",
  union: "union berlin",
  psg: "paris saint-germain",
  paris: "paris saint-germain",
  om: "marseille",
  ol: "olympique lyon",
  lyon: "olympique lyon",
  monaco: "monaco",
  lens: "racing club de lens",
  rennes: "rennais",
  juve: "juventus",
  inter: "inter milano",
  "inter milan": "inter milano",
  milan: "ac milan",
  napoli: "napoli",
  roma: "as roma",
  lazio: "lazio",
  atalanta: "atalanta",
};

module.exports = { LEAGUES, LEAGUE_LABELS, LEAGUE_EMOJIS, TEAM_ALIASES };
